"""empty message

Revision ID: 015cf060d3bc
Revises: 1361f5f698e2
Create Date: 2022-09-27 16:15:28.718930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015cf060d3bc'
down_revision = '1361f5f698e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'age')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('age', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
